company_data_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: your_postgres_user
      password: your_postgres_password
      port: 5432
      dbname: your_database
      schema: cleaned
      threads: 4
